//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharaSparksvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class charasparkdevEntities : DbContext
    {
        public charasparkdevEntities()
            : base("name=charasparkdevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<error_log> error_log { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<wish_status> wish_status { get; set; }
        public virtual DbSet<wish> wishes { get; set; }
    }
}
